version: '3'

services:
  redis:
    image: redis

  web:
    # build: .
    image: staleflippant/primeservice:web
    command: sh -c "celery -A primeservice worker --loglevel=info & celery -A primeservice beat --loglevel=info & python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis

  web-2:
    # build: .
    image: staleflippant/primeservice:web
    command: sh -c "celery -A primeservice worker --loglevel=info & celery -A primeservice beat --loglevel=info & python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app-2
    ports:
      - "12345:8000"
    depends_on:
      - redis
    links:
      - redis

  web-3:
    # build: .
    image: staleflippant/primeservice:web
    command: sh -c "celery -A primeservice worker --loglevel=info & celery -A primeservice beat --loglevel=info & python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app-3
    ports:
      - "12344:8000"
    depends_on:
      - redis
    links:
      - redis
