# Generated by Django 4.2 on 2023-05-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimeNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
        ),
    ]
