# Generated by Django 4.2 on 2023-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primes", "0002_primenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primenumber",
            name="number",
            field=models.IntegerField(unique=True),
        ),
    ]
